const JWT_ADMIN_PASSOWORDKEY = process.env.JWT_ADMIN_PASSOWORDKEY
const JWT_USER_PASSOWORDKEY = process.env.JWT_USER_PASSOWORDKEY

module.exports = {
    JWT_ADMIN_PASSOWORDKEY,JWT_USER_PASSOWORDKEY
}